CREATE DATABASE EMPRESA2;
use empresa2;
CREATE TABLE DEPARTAMENTO (
    DNUMERO INT PRIMARY KEY,
    DNOME VARCHAR(30),
    CPF_GERENTE VARCHAR(15)
);
CREATE TABLE FUNCIONARIO (
    CPF VARCHAR(15) PRIMARY KEY,
    FUNCIONARIO_CPF VARCHAR(15), -- Supervisor
    DEPARTAMENTO_DNUMERO INT,
    PNOME VARCHAR(60),
    UNOME VARCHAR(30),
    ENDERECO VARCHAR(80),
    SEXO CHAR(1),
    SALARIO REAL,
    FOREIGN KEY (FUNCIONARIO_CPF) REFERENCES FUNCIONARIO(CPF),
    FOREIGN KEY (DEPARTAMENTO_DNUMERO) REFERENCES DEPARTAMENTO(DNUMERO)
);
ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT fk_gerente FOREIGN KEY (CPF_GERENTE) REFERENCES FUNCIONARIO(CPF);
CREATE TABLE DEPENDENTE (
    CPF VARCHAR(15),
    NOME_DEPENDENTE VARCHAR(60),
    PARENTESCO VARCHAR(20),
    FOREIGN KEY (CPF) REFERENCES FUNCIONARIO(CPF)
);
CREATE TABLE PROJETO (
    PNUMERO INT PRIMARY KEY,
    PJNOME VARCHAR(30),
    DNUMERO INT,
    FOREIGN KEY (DNUMERO) REFERENCES DEPARTAMENTO(DNUMERO)
);
CREATE TABLE TRABALHA_EM (
    FUNCIONARIO_CPF VARCHAR(15),
    PROJETO_PNUMERO INT,
    FOREIGN KEY (FUNCIONARIO_CPF) REFERENCES FUNCIONARIO(CPF),
    FOREIGN KEY (PROJETO_PNUMERO) REFERENCES PROJETO(PNUMERO)
);

SELECT PNOME, UNOME, SALARIO
FROM FUNCIONARIO;

SELECT * FROM FUNCIONARIO
WHERE SALARIO > 30000;

SELECT FUNCIONARIO_CPF
FROM TRABALHA_EM
WHERE PROJETO_PNUMERO IN (1, 2, 3);

SELECT DNOME
FROM DEPARTAMENTO
ORDER BY DNOME ASC;

SELECT F.PNOME, F.UNOME, F.ENDERECO
FROM FUNCIONARIO F
INNER JOIN DEPARTAMENTO D ON F.DEPARTAMENTO_DNUMERO = D.DNUMERO
WHERE D.DNOME = 'Pesquisa';

SELECT F.PNOME AS FUNCIONARIO_PNOME, F.UNOME AS FUNCIONARIO_UNOME,
       S.PNOME AS SUPERVISOR_PNOME, S.UNOME AS SUPERVISOR_UNOME
FROM FUNCIONARIO F
LEFT JOIN FUNCIONARIO S ON F.FUNCIONARIO_CPF = S.CPF;

SELECT COUNT(DISTINCT SALARIO) AS SALARIOS_DISTINTOS
FROM FUNCIONARIO;

SELECT MAX(SALARIO) AS MAIOR_SALARIO,
       MIN(SALARIO) AS MENOR_SALARIO
FROM FUNCIONARIO;

SELECT DEPARTAMENTO_DNUMERO,
       COUNT(*) AS TOTAL_FUNCIONARIOS,
       AVG(SALARIO) AS MEDIA_SALARIAL
FROM FUNCIONARIO
GROUP BY DEPARTAMENTO_DNUMERO;

SELECT PROJETO_PNUMERO, COUNT(*) AS TOTAL_FUNCIONARIOS
FROM TRABALHA_EM
GROUP BY PROJETO_PNUMERO
HAVING COUNT(*) > 2;

SELECT PNOME, UNOME
FROM FUNCIONARIO
WHERE CPF IN (
    SELECT CPF
    FROM DEPENDENTE
    GROUP BY CPF
    HAVING COUNT(*) >= 2
);

SELECT F.PNOME, F.UNOME
FROM FUNCIONARIO F
WHERE EXISTS (
    SELECT 1
    FROM DEPARTAMENTO D
    WHERE D.CPF_GERENTE = F.CPF
)
AND EXISTS (
    SELECT 1
    FROM DEPENDENTE D
    WHERE D.CPF = F.CPF
);

SELECT DISTINCT F.PNOME, F.UNOME
FROM FUNCIONARIO F
JOIN TRABALHA_EM TE ON F.CPF = TE.FUNCIONARIO_CPF
JOIN PROJETO P ON TE.PROJETO_PNUMERO = P.PNUMERO
JOIN DEPARTAMENTO D ON P.DNUMERO = D.DNUMERO
WHERE D.DNOME = 'Pesquisa'
  AND F.CPF IN (SELECT CPF FROM DEPENDENTE)
  AND F.SALARIO > (
      SELECT AVG(SALARIO)
      FROM FUNCIONARIO
  );
#GABRIEL FAGUNDES DOS SANTOS, ADS TURMA B
